#!/bin/bash

# Array of salt quotes
quotes=(
"The best way to predict the future is to invent it."
"Do one thing every day that scares you."
"Life is what happens when you’re busy making other plans."
"Happiness depends upon ourselves."
"In the middle of every difficulty lies opportunity."
"Success is not final, failure is not fatal: It is the courage to continue that counts."
"The only limit to our realization of tomorrow is our doubts of today."
"What you get by achieving your goals is not as important as what you become by achieving your goals."
"Do not go where the path may lead, go instead where there is no path and leave a trail."
"The journey of a thousand miles begins with one step."
"You miss 100% of the shots you don’t take."
"Believe you can and you’re halfway there."
"Act as if what you do makes a difference. It does."
"The only way to do great work is to love what you do."
"Don’t watch the clock; do what it does. Keep going."
"If opportunity doesn’t knock, build a door."
"A room without books is like a body without a soul."
"Try to be a rainbow in someone’s cloud."
"What lies behind us and what lies before us are tiny matters compared to what lies within us."
"It is never too late to be what you might have been."
"Everything you’ve ever wanted is on the other side of fear."
"The only person you should try to be better than is the person you were yesterday."
"You must be the change you wish to see in the world."
"Do not wait to strike till the iron is hot; but make it hot by striking."
"Whether you think you can or think you can’t, you’re right."
"It always seems impossible until it’s done."
"Keep your face always toward the sunshine—and shadows will fall behind you."
"We cannot direct the wind, but we can adjust the sails."
"The harder you work for something, the greater you’ll feel when you achieve it."
"Dream big and dare to fail."
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart."
"Your time is limited, so don’t waste it living someone else’s life."
"Success usually comes to those who are too busy to be looking for it."
"Don’t be afraid to give up the good to go for the great."
"I find that the harder I work, the more luck I seem to have."
"The purpose of our lives is to be happy."
"Life is really simple, but we insist on making it complicated."
"May you live all the days of your life."
"Do what you can, with what you have, where you are."
"A journey is best measured in friends, rather than miles."
"Happiness is not something ready-made. It comes from your own actions."
"The greatest glory in living lies not in never falling, but in rising every time we fall."
"You don’t have to be great to start, but you have to start to be great."
"Life is short, and it is up to you to make it sweet."
"Success is walking from failure to failure with no loss of enthusiasm."
"The mind is everything. What you think you become."
"The best revenge is massive success."
"Don’t count the days, make the days count."
"Nothing is impossible, the word itself says 'I’m possible'!"
"Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain."
"Turn your wounds into wisdom."
"Keep going. Everything you need will come to you at the perfect time."
"Fall seven times and stand up eight."
"Don’t let yesterday take up too much of today."
"You are never too old to set another goal or to dream a new dream."
"A person who never made a mistake never tried anything new."
"If you want to lift yourself up, lift up someone else."
"You can’t cross the sea merely by standing and staring at the water."
"The best way out is always through."
"Life is made of ever so many partings welded together."
"Be yourself; everyone else is already taken."
"Do not let making a living prevent you from making a life."
"It does not matter how slowly you go as long as you do not stop."
"Don’t judge each day by the harvest you reap but by the seeds that you plant."
"In three words I can sum up everything I’ve learned about life: it goes on."
"Do not fear failure but rather fear not trying."
"You only live once, but if you do it right, once is enough."
"Happiness is not by chance, but by choice."
"Courage is grace under pressure."
"The secret of getting ahead is getting started."
"Life is a journey that must be traveled no matter how bad the roads and accommodations."
"Life isn’t about finding yourself. Life is about creating yourself."
"Difficulties in life don’t come to destroy you. They come to help you realize your hidden potential."
"You can’t go back and change the beginning, but you can start where you are and change the ending."
"Energy and persistence conquer all things."
"Happiness is a warm puppy."
"What we achieve inwardly will change outer reality."
"To succeed in life, you need two things: ignorance and confidence."
"Do not let what you cannot do interfere with what you can do."
"The biggest adventure you can take is to live the life of your dreams."
"Keep your eyes on the stars, and your feet on the ground."
"The secret to success is to know something nobody else knows."
"What we think, we become."
"Be kind whenever possible. It is always possible."
"We do not remember days, we remember moments."
"A goal is a dream with a deadline."
"You are braver than you believe, stronger than you seem, and smarter than you think."
"Success is not how high you have climbed, but how you make a positive difference to the world."
"Do what you love, and you will never work a day in your life."
"Happiness is not having what you want. It is wanting what you have."
"What consumes your mind controls your life."
"Small deeds done are better than great deeds planned."
"The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty."
"Keep your face to the sunshine and you cannot see a shadow."
"The best way to cheer yourself up is to try to cheer somebody else up."
"Challenges are what make life interesting and overcoming them is what makes life meaningful."
"Life is short, and truth works far and lives long."
"Don’t let the noise of others’ opinions drown out your own inner voice."
"We may encounter many defeats but we must not be defeated."
"Happiness is not something you postpone for the future; it is something you design for the present."
"Try not to become a man of success, but rather try to become a man of value."
"If you do what you’ve always done, you’ll get what you’ve always gotten."
"The greatest pleasure in life is doing what people say you cannot do."
"If you want to live a happy life, tie it to a goal, not to people or things."
"It is our choices that show what we truly are, far more than our abilities."
"You can’t build a reputation on what you are going to do."
"You cannot swim for new horizons until you have courage to lose sight of the shore."
"Hardships often prepare ordinary people for an extraordinary destiny."
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle."
"Everything has beauty, but not everyone sees it."
"You don’t always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens."
"Happiness is when what you think, what you say, and what you do are in harmony."
"To live is the rarest thing in the world. Most people exist, that is all."
"A day without laughter is a day wasted."
"Life is either a daring adventure or nothing at all."
"When one door of happiness closes, another opens."
"The only impossible journey is the one you never begin."
"Your life does not get better by chance, it gets better by change."
"Nothing great was ever achieved without enthusiasm."
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact."
"The best way to find yourself is to lose yourself in the service of others."
"Happiness is not an ideal of reason but of imagination."
"The journey is the reward."
"Great minds discuss ideas; average minds discuss events; small minds discuss people."
"Don’t let schooling interfere with your education."
"You are confined only by the walls you build yourself."
"Do what is right, not what is easy nor what is popular."
"Life is really simple, but we insist on making it complicated."
"Act as if what you do makes a difference. It does."
"In the end, we will remember not the words of our enemies, but the silence of our friends."
"A year from now you may wish you had started today."
"Don’t let the fear of losing be greater than the excitement of winning."
"Go confidently in the direction of your dreams. Live the life you have imagined."
"Happiness is not out there, it’s in you."
"Success is the sum of small efforts repeated day in and day out."
"Life is 10% what happens to us and 90% how we react to it."
"Don’t wait. The time will never be just right."
"To succeed, we must first believe that we can."
)

# Number of grains
num_grains=1000
num_quotes=${#quotes[@]}

# Loop to create files
for ((i=1; i<=num_grains; i++)); do
    quote_index=$(( (i-1) % num_quotes ))
    echo "${quotes[$quote_index]}" > "Page_$i"
done
